# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import learning_service_pb2 as learning__service__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in learning_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LinguisticServiceStub(object):
    """Service xử lý ngôn ngữ học (Kernel)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Tokenize = channel.unary_unary(
                '/core_linguistic.learning.v1.LinguisticService/Tokenize',
                request_serializer=learning__service__pb2.TokenizeRequest.SerializeToString,
                response_deserializer=learning__service__pb2.TokenizeResponse.FromString,
                _registered_method=True)
        self.GetHanViet = channel.unary_unary(
                '/core_linguistic.learning.v1.LinguisticService/GetHanViet',
                request_serializer=learning__service__pb2.GetHanVietRequest.SerializeToString,
                response_deserializer=learning__service__pb2.GetHanVietResponse.FromString,
                _registered_method=True)


class LinguisticServiceServicer(object):
    """Service xử lý ngôn ngữ học (Kernel)
    """

    def Tokenize(self, request, context):
        """Tách từ và phân tích ngữ pháp
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHanViet(self, request, context):
        """Tra cứu âm Hán-Việt (hỗ trợ cả từ đơn và từ ghép)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LinguisticServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Tokenize': grpc.unary_unary_rpc_method_handler(
                    servicer.Tokenize,
                    request_deserializer=learning__service__pb2.TokenizeRequest.FromString,
                    response_serializer=learning__service__pb2.TokenizeResponse.SerializeToString,
            ),
            'GetHanViet': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHanViet,
                    request_deserializer=learning__service__pb2.GetHanVietRequest.FromString,
                    response_serializer=learning__service__pb2.GetHanVietResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'core_linguistic.learning.v1.LinguisticService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('core_linguistic.learning.v1.LinguisticService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LinguisticService(object):
    """Service xử lý ngôn ngữ học (Kernel)
    """

    @staticmethod
    def Tokenize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core_linguistic.learning.v1.LinguisticService/Tokenize',
            learning__service__pb2.TokenizeRequest.SerializeToString,
            learning__service__pb2.TokenizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHanViet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core_linguistic.learning.v1.LinguisticService/GetHanViet',
            learning__service__pb2.GetHanVietRequest.SerializeToString,
            learning__service__pb2.GetHanVietResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MemoryServiceStub(object):
    """Service quản lý thuật toán ghi nhớ (Learning OS Kernel)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateMemoryState = channel.unary_unary(
                '/core_linguistic.learning.v1.MemoryService/UpdateMemoryState',
                request_serializer=learning__service__pb2.UpdateMemoryStateRequest.SerializeToString,
                response_deserializer=learning__service__pb2.MemoryObject.FromString,
                _registered_method=True)
        self.GetDueItems = channel.unary_unary(
                '/core_linguistic.learning.v1.MemoryService/GetDueItems',
                request_serializer=learning__service__pb2.GetDueItemsRequest.SerializeToString,
                response_deserializer=learning__service__pb2.GetDueItemsResponse.FromString,
                _registered_method=True)


class MemoryServiceServicer(object):
    """Service quản lý thuật toán ghi nhớ (Learning OS Kernel)
    """

    def UpdateMemoryState(self, request, context):
        """Cập nhật trạng thái ghi nhớ sau khi người dùng ôn tập
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDueItems(self, request, context):
        """Lấy danh sách các từ vựng đến hạn ôn tập (Due items)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateMemoryState': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMemoryState,
                    request_deserializer=learning__service__pb2.UpdateMemoryStateRequest.FromString,
                    response_serializer=learning__service__pb2.MemoryObject.SerializeToString,
            ),
            'GetDueItems': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDueItems,
                    request_deserializer=learning__service__pb2.GetDueItemsRequest.FromString,
                    response_serializer=learning__service__pb2.GetDueItemsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'core_linguistic.learning.v1.MemoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('core_linguistic.learning.v1.MemoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryService(object):
    """Service quản lý thuật toán ghi nhớ (Learning OS Kernel)
    """

    @staticmethod
    def UpdateMemoryState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core_linguistic.learning.v1.MemoryService/UpdateMemoryState',
            learning__service__pb2.UpdateMemoryStateRequest.SerializeToString,
            learning__service__pb2.MemoryObject.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDueItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core_linguistic.learning.v1.MemoryService/GetDueItems',
            learning__service__pb2.GetDueItemsRequest.SerializeToString,
            learning__service__pb2.GetDueItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
