# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import learning_service_pb2 as learning__service__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in learning_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LinguisticServiceStub(object):
    """Service handling linguistic analysis (Kernel)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TokenizeText = channel.unary_unary(
                '/core_linguistic.learning.v1.LinguisticService/TokenizeText',
                request_serializer=learning__service__pb2.TokenizeTextRequest.SerializeToString,
                response_deserializer=learning__service__pb2.TokenizeTextResponse.FromString,
                _registered_method=True)
        self.GetSinoVietnamese = channel.unary_unary(
                '/core_linguistic.learning.v1.LinguisticService/GetSinoVietnamese',
                request_serializer=learning__service__pb2.GetSinoVietnameseRequest.SerializeToString,
                response_deserializer=learning__service__pb2.GetSinoVietnameseResponse.FromString,
                _registered_method=True)


class LinguisticServiceServicer(object):
    """Service handling linguistic analysis (Kernel)
    """

    def TokenizeText(self, request, context):
        """Analyzes text into tokens
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSinoVietnamese(self, request, context):
        """Retrieves Sino-Vietnamese phonetics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LinguisticServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TokenizeText': grpc.unary_unary_rpc_method_handler(
                    servicer.TokenizeText,
                    request_deserializer=learning__service__pb2.TokenizeTextRequest.FromString,
                    response_serializer=learning__service__pb2.TokenizeTextResponse.SerializeToString,
            ),
            'GetSinoVietnamese': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSinoVietnamese,
                    request_deserializer=learning__service__pb2.GetSinoVietnameseRequest.FromString,
                    response_serializer=learning__service__pb2.GetSinoVietnameseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'core_linguistic.learning.v1.LinguisticService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('core_linguistic.learning.v1.LinguisticService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LinguisticService(object):
    """Service handling linguistic analysis (Kernel)
    """

    @staticmethod
    def TokenizeText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core_linguistic.learning.v1.LinguisticService/TokenizeText',
            learning__service__pb2.TokenizeTextRequest.SerializeToString,
            learning__service__pb2.TokenizeTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSinoVietnamese(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core_linguistic.learning.v1.LinguisticService/GetSinoVietnamese',
            learning__service__pb2.GetSinoVietnameseRequest.SerializeToString,
            learning__service__pb2.GetSinoVietnameseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MemoryServiceStub(object):
    """Service managing memory algorithms (Learning OS Kernel)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateMemoryState = channel.unary_unary(
                '/core_linguistic.learning.v1.MemoryService/UpdateMemoryState',
                request_serializer=learning__service__pb2.UpdateMemoryStateRequest.SerializeToString,
                response_deserializer=learning__service__pb2.MemoryObject.FromString,
                _registered_method=True)
        self.GetDueItems = channel.unary_unary(
                '/core_linguistic.learning.v1.MemoryService/GetDueItems',
                request_serializer=learning__service__pb2.GetDueItemsRequest.SerializeToString,
                response_deserializer=learning__service__pb2.GetDueItemsResponse.FromString,
                _registered_method=True)


class MemoryServiceServicer(object):
    """Service managing memory algorithms (Learning OS Kernel)
    """

    def UpdateMemoryState(self, request, context):
        """Updates memory state after a user review
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDueItems(self, request, context):
        """Retrieves vocabulary items due for review
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateMemoryState': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMemoryState,
                    request_deserializer=learning__service__pb2.UpdateMemoryStateRequest.FromString,
                    response_serializer=learning__service__pb2.MemoryObject.SerializeToString,
            ),
            'GetDueItems': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDueItems,
                    request_deserializer=learning__service__pb2.GetDueItemsRequest.FromString,
                    response_serializer=learning__service__pb2.GetDueItemsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'core_linguistic.learning.v1.MemoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('core_linguistic.learning.v1.MemoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryService(object):
    """Service managing memory algorithms (Learning OS Kernel)
    """

    @staticmethod
    def UpdateMemoryState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core_linguistic.learning.v1.MemoryService/UpdateMemoryState',
            learning__service__pb2.UpdateMemoryStateRequest.SerializeToString,
            learning__service__pb2.MemoryObject.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDueItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core_linguistic.learning.v1.MemoryService/GetDueItems',
            learning__service__pb2.GetDueItemsRequest.SerializeToString,
            learning__service__pb2.GetDueItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AgentServiceStub(object):
    """Service for AI Agents to extract knowledge
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestContent = channel.unary_unary(
                '/core_linguistic.learning.v1.AgentService/IngestContent',
                request_serializer=learning__service__pb2.IngestContentRequest.SerializeToString,
                response_deserializer=learning__service__pb2.IngestContentResponse.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """Service for AI Agents to extract knowledge
    """

    def IngestContent(self, request, context):
        """Processes raw text into knowledge objects
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestContent': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestContent,
                    request_deserializer=learning__service__pb2.IngestContentRequest.FromString,
                    response_serializer=learning__service__pb2.IngestContentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'core_linguistic.learning.v1.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('core_linguistic.learning.v1.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """Service for AI Agents to extract knowledge
    """

    @staticmethod
    def IngestContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core_linguistic.learning.v1.AgentService/IngestContent',
            learning__service__pb2.IngestContentRequest.SerializeToString,
            learning__service__pb2.IngestContentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
